### ISSUE TITLE
Function to close the connection and record/send to asciinema?

### ISSUE THREAD

**Issue by lstep** [mkishere/sshsyrup#21]
I wanted to implement the exit function in the fake shell but I could not find what to call to end the current session (and trigger the asciinema processing)?

**Comment by victpork** [comment]
Actually exit was hardcoded in [shell loop](https://github.com/mkishere/sshsyrup/blob/6103194a464944d25d3671f1faaa2e3502c9589d/os/shell.go#L63). Similar commands should be implemented this way if no extra work needed to be done.

**Comment by victpork** [comment]
I’ll close the issue now, reopen it when there is a use case for this
