### ISSUE TITLE
Move configuration to viper

### ISSUE THREAD

**Issue by victpork** [mkishere/sshsyrup#22]
Should we move configuration management to [Viper](https://www.github.com/spf13/viper) library? With support of error handling, default values and multiple config locations, looks like a better choice for current homemade solution.

Any cons of adapting the library?

**Comment by jdel** [comment]
I have been using both cobra for the command line arguments and viper for the configuration.

You can have a look at my go repos to see both are pretty easy to implement. 

GIve me a shout if you need a hand.

**Comment by victpork** [comment]
Oh I should be meaning viper :( Anyway I'm looking forward to it, just not sure if there are any caveats

**Comment by jdel** [comment]
Not that I know of, but I'm pretty new to go. These libraries have been stable and have gone through many updates and rebuilds. The ability to link command line flags with viper configuration items is really useful.

**Comment by victpork** [comment]
Speaking of command line flags/arguments, any flags come into your mind you'll need it?
