### ISSUE TITLE
[Docker] Provide ssh-syrup automated build docker image

### ISSUE THREAD

**Issue by jdel** [mkishere/sshsyrup#25]
I can help provide an automated docker image for ssh-syrup if interested. 

I haven't had time to check on ssh-syrup regularly because you commit a lot, but I'm definitely going to use a dockerized version of it at some point so I might as well submit a PR.

If this is something you want, you can already [create a docker hub account](hub.docker.com).

**Comment by victpork** [comment]
Glad to have it dockerized! Sure feel free to submit a PR. I might as well put it in CI script so that will help to build a docker image once I confirm a release.

**Comment by jdel** [comment]
This can all be done with a docker hub build hook. I will get in touch when I have some time for this. 

Have you got a gitter or slack somewhere ?

**Comment by victpork** [comment]
Actually I have created a docker account and linked with GitHub already. Once you have submit a PR with dockerfile I'll do the rest.

**Comment by lstep** [comment]
Sorry, I was faster :-) I put a PR with a Dockerfile. 
The current problem is that you hardcoded all the file paths in the code, so we can't put the files outside of the Docker instance (which would be a little more practical, especially for the logs).

**Comment by victpork** [comment]
I think I'll do both:
1. Expose the config param to env variables
2. Allow to designate config file path via argument

**Comment by lstep** [comment]
I think adding a cmdline parameter that would set the "root" of all the extra loaded files (commands.txt, logs/, etc.) would be nice because currently there are too much hardcoded paths.

**Comment by victpork** [comment]
Docker image setup at Hub. You may now do with dockerized build with `docker pull mkishere/sshsyrup` for nightly. There's a few rough edges yet (mainly on the configuration), I'll smooth them over the next few iterations.
