### ISSUE TITLE
Implement essential set of coreutils

### ISSUE THREAD

**Issue by victpork** [mkishere/sshsyrup#3]
Implement coreutils command set for the shell, at the very least output something meaningful that could fool someone

**Comment by lstep** [comment]
If you don't have yet  a command, you can return a "random" generated error. I think Kippo does this (or it was another SSH honeypot?)

**Comment by victpork** [comment]
Good idea. I'll try to implement the interim solution first.

**Comment by victpork** [comment]
I'm closing this and breaking down into issues on specific command.
